"""Build figures, tables and number macros for the customer-service report.

Reads ``cs_harness/results/results.json`` (written by analyze.py) and the raw
tau2 conversation records, and writes into ``cs_harness/report/``. Every
number in the PDF comes from these files.

    .venv/Scripts/python.exe cs_harness/build_report.py      (Aegis venv, repo root)
    cd cs_harness/report && pdflatex cs_report.tex && pdflatex cs_report.tex
"""

from __future__ import annotations

import glob
import gzip
import json
import os
from math import comb
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent
SIMS = ROOT.parent / "third_party" / "tau2-bench" / "data" / "simulations"
OUT = ROOT / "report"
MAIN = ["A", "B", "D", "E"]
LABEL = {"A": "Plain agent", "B": "Code-checked", "D": "AI-checked", "E": "Stronger model",
         "A-h": "Plain agent", "B-h": "Code-checked"}
COLOR = {"A": "#eda100", "B": "#2a78d6", "D": "#e34948", "E": "#1baf7a"}
WRITES = {"book_reservation", "cancel_reservation", "send_certificate",
          "update_reservation_baggages", "update_reservation_flights",
          "update_reservation_passengers"}


def tex(value) -> str:
    s = str(value).replace("\\", "\x00")
    for old, new in (("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"), ("_", r"\_"),
                     ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\^{}")):
        s = s.replace(old, new)
    s = s.replace("\x00", r"\textbackslash{}")
    for bad, good in (("\u2019", "'"), ("\u2018", "'"), ("\u201c", "``"), ("\u201d", "''"),
                      ("\u2014", "--"), ("\u2013", "--"), ("\u2026", "..."), ("\u00e9", r"\'e")):
        s = s.replace(bad, good)
    return s.encode("ascii", "ignore").decode()


def pct(x) -> str:
    return "--" if x is None else f"{100 * x:.1f}"


def trim(text: str, n: int) -> str:
    text = " ".join((text or "").split())
    return text if len(text) <= n else text[: n - 1].rstrip() + "..."


RUNS = ROOT / "results" / "runs"
"""Committed, gzipped copies of every run the report uses (the evidence)."""


def load_sims(run: str) -> dict | None:
    """Load a run from the committed archive, else from tau2's simulations folder."""
    gz = RUNS / f"{run}.json.gz"
    if gz.exists():
        with gzip.open(gz, "rt", encoding="utf-8") as fh:
            return json.load(fh)
    files = glob.glob(str(SIMS / run / "**" / "*.json"), recursive=True)
    return json.load(open(max(files, key=os.path.getsize), encoding="utf-8")) if files else None


def all_run_names() -> list[str]:
    names = {p.name.removesuffix(".json.gz") for p in RUNS.glob("*.json.gz")}
    names |= {Path(d).name for d in glob.glob(str(SIMS / "*"))}
    return sorted(names)


def per_task(data: dict) -> dict[str, list[float]]:
    out: dict[str, list[float]] = {}
    for s in data["simulations"]:
        out.setdefault(str(s["task_id"]), []).append(float(s["reward_info"]["reward"]))
    return out


def pass_k(rewards_by_task: dict[str, list[float]], k: int) -> float:
    vals = []
    for r in rewards_by_task.values():
        c = int(sum(x >= 1.0 for x in r))
        vals.append(comb(c, k) / comb(len(r), k) if len(r) >= k else float("nan"))
    return float(np.nanmean(vals))


def boot_ci(values, n_boot=10000, seed=0):
    v = np.asarray(values, dtype=float)
    rng = np.random.default_rng(seed)
    m = v[rng.integers(0, len(v), size=(n_boot, len(v)))].mean(axis=1)
    return float(v.mean()), float(np.percentile(m, 2.5)), float(np.percentile(m, 97.5))


def guard_events(sim: dict):
    for m in sim.get("messages", []):
        rd = m.get("raw_data") if isinstance(m.get("raw_data"), dict) else {}
        yield from rd.get("aegis_guard", []) or []


def _norm(v) -> str:
    return json.dumps(v, sort_keys=True) if isinstance(v, (dict, list)) else str(v)


def false_blocks(data: dict) -> tuple[int, int]:
    tasks = {str(t["id"]): t for t in data["tasks"]}
    blocked = fb = 0
    for s in data["simulations"]:
        gold = [(a["name"], a.get("arguments") or {}) for a in
                (tasks[str(s["task_id"])].get("evaluation_criteria") or {}).get("actions") or []]
        for e in guard_events(s):
            if e.get("outcome") != "blocked":
                continue
            for call in e.get("calls", []):
                if call["name"] in WRITES:
                    blocked += 1
                    fb += any(gn == call["name"] and all(_norm((call.get("arguments") or {}).get(k)) == _norm(v)
                                                         for k, v in ga.items()) for gn, ga in gold)
    return blocked, fb


# ------------------------------------------------------------------ macros


def macros(res: dict, dev: dict) -> list[str]:
    lines = ["% Generated by cs_harness/build_report.py -- do not edit."]

    def cmd(name, value):
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    tag = {"A": "Plain", "B": "Code", "D": "Llm", "E": "Strong", "A-h": "PlainHuman", "B-h": "CodeHuman"}
    for key, a in res["arms"].items():
        t = tag[key]
        mean, lo, hi = boot_ci(list(a["per_task"].values()))
        kmax = max(int(k) for k in a["pass_k"])
        cmd(f"{t}Pass", pct(a["pass_k"]["1"]))
        cmd(f"{t}PassCI", f"[{pct(lo)}, {pct(hi)}]")
        cmd(f"{t}PassK", pct(a["pass_k"][str(kmax)]))
        cmd(f"{t}K", str(kmax))
        cmd(f"{t}Db", pct(a["db_match"]))
        cmd(f"{t}CostConv", f"{a['cost_per_conversation']:.4f}")
        cmd(f"{t}CostSuccess", f"{a['cost_per_success']:.3f}" if a["cost_per_success"] else "--")
        cmd(f"{t}Trials", str(a["trials"]))
        cmd(f"{t}Convs", str(a["conversations"]))
        g = a["guard"]
        cmd(f"{t}Blocked", str(g["blocked_write_calls"]))
        cmd(f"{t}FalseBlocks", str(g["false_blocks"]))
        cmd(f"{t}Repaired", str(g["repaired"]))
    ctag = {"B vs A": "BvA", "B vs D": "BvD", "B vs E": "BvE", "D vs A": "DvA", "B-h vs A-h": "BhvAh"}
    for name, c in res["comparisons"].items():
        t = ctag[name]
        cmd(f"{t}Diff", f"{100 * c['diff']:+.1f}")
        cmd(f"{t}CI", f"[{100 * c['ci'][0]:+.1f}, {100 * c['ci'][1]:+.1f}]")
        cmd(f"{t}P", f"{c['p_wilcoxon']:.3f}")
        cmd(f"{t}Better", str(c["tasks_better"]))
        cmd(f"{t}Worse", str(c["tasks_worse"]))
    cmd("NTasks", str(res["arms"]["A"]["n_tasks"]))
    test_spend = sum(a["cost_total"] for a in res["arms"].values())
    cmd("TestSpend", f"{test_spend:.2f}")
    cmd("DevSpend", f"{dev['spend']:.2f}")
    cmd("StudySpend", f"{test_spend + dev['spend']:.2f}")
    for k, v in dev["rows"].items():
        cmd(f"Dev{k}PassOne", pct(v["p1"]))
        cmd(f"Dev{k}PassTwo", pct(v["p2"]))
        cmd(f"Dev{k}FalseBlocks", "--" if v["fb"] is None else str(v["fb"]))
    return lines


# ------------------------------------------------------------------ tables


def table_main(res: dict) -> str:
    rows = [
        ("A", "Plain agent", "gpt-4o-mini", "none"),
        ("B", "Harness, code checker", "gpt-4o-mini", "policy as code"),
        ("D", "Harness, AI checker", "gpt-4o-mini", "same model judges"),
        ("E", "Plain stronger model", "gpt-4.1-mini", "none"),
    ]
    out = ["\\begin{tabular}{llrrrrrr}", "\\toprule",
           "Arm & Agent & Solved (\\%) & Solved every try & DB correct & \\$/conv. & \\$/solved & Blocks (false) \\\\",
           "\\midrule"]
    for key, name, model, _ in rows:
        a = res["arms"][key]
        mean, lo, hi = boot_ci(list(a["per_task"].values()))
        g = a["guard"]
        blocks = "--" if key in ("A", "E") else f"{g['blocked_write_calls']} ({g['false_blocks']})"
        out.append(
            f"{key} & {name}, {tex(model)} & {pct(mean)} {{\\scriptsize[{pct(lo)}, {pct(hi)}]}} & "
            f"{pct(a['pass_k']['4'])}\\% & {pct(a['db_match'])}\\% & {a['cost_per_conversation']:.4f} & "
            f"{a['cost_per_success']:.3f} & {blocks} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def table_comparisons(res: dict) -> str:
    names = [("B vs A", "Code-checked vs plain"), ("B vs D", "Code checker vs AI checker"),
             ("B vs E", "Code-checked cheap model vs plain stronger model"),
             ("D vs A", "AI-checked vs plain"),
             ("B-h vs A-h", "Code-checked vs plain, human-like customer")]
    out = ["\\begin{tabular}{lrrrr}", "\\toprule",
           "Comparison (paired by task) & Difference & 95\\% CI & Wilcoxon $p$ & Tasks better / worse \\\\",
           "\\midrule"]
    for key, name in names:
        c = res["comparisons"][key]
        out.append(f"{name} & {100 * c['diff']:+.1f} pts & [{100 * c['ci'][0]:+.1f}, {100 * c['ci'][1]:+.1f}] "
                   f"& {c['p_wilcoxon']:.3f} & {c['tasks_better']} / {c['tasks_worse']} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def table_dev(dev: dict) -> str:
    out = ["\\begin{tabular}{lrrr}", "\\toprule",
           "Development set (30 tasks $\\times$ 2 tries) & Solved (\\%) & Solved both tries (\\%) & False blocks \\\\",
           "\\midrule"]
    for key, label in (("Plain", "Plain agent"), ("One", "Harness, first version"),
                       ("Two", "Harness, final version")):
        v = dev["rows"][key]
        out.append(f"{label} & {pct(v['p1'])} & {pct(v['p2'])} & {'--' if v['fb'] is None else v['fb']} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def first_customer_text(sim: dict) -> str:
    for m in sim.get("messages", []):
        if m.get("role") == "user" and m.get("content"):
            return m["content"]
    return ""


def table_examples(plain: dict, code: dict) -> str:
    """Real test conversations: fixes (plain failed, harness succeeded after a block) and one cost."""
    p_rates = {k: float(np.mean(v)) for k, v in per_task(plain).items()}
    rows = []
    for s in sorted(code["simulations"], key=lambda s: (str(s["task_id"]), s.get("trial", 0))):
        tid = str(s["task_id"])
        if len([r for r in rows if r[0] == "fix"]) >= 3:
            break
        if p_rates.get(tid, 1) > 0 or s["reward_info"]["reward"] < 1 or tid in {r[1] for r in rows}:
            continue
        blocks = [e for e in guard_events(s) if e.get("outcome") == "blocked"]
        if not blocks:
            continue
        b = blocks[0]
        call = b["calls"][0]["name"]
        v = next(iter(b["violations"].values()))[0]
        rows.append(("fix", tid, first_customer_text(s), call, v, "Solved"))
    c_rates = {k: float(np.mean(v)) for k, v in per_task(code).items()}
    for s in sorted(code["simulations"], key=lambda s: (str(s["task_id"]), s.get("trial", 0))):
        tid = str(s["task_id"])
        if c_rates.get(tid, 0) >= p_rates.get(tid, 0) or s["reward_info"]["reward"] >= 1:
            continue
        blocks = [e for e in guard_events(s) if e.get("outcome") == "blocked"]
        if not blocks:
            continue
        b = blocks[0]
        rows.append(("cost", tid, first_customer_text(s), b["calls"][0]["name"],
                     next(iter(b["violations"].values()))[0], "Failed"))
        break
    col = ">{\\raggedright\\arraybackslash}p"
    out = [f"\\begin{{tabular}}{{{col}{{0.05\\linewidth}}{col}{{0.24\\linewidth}}{col}{{0.21\\linewidth}}"
           f"{col}{{0.32\\linewidth}}{col}{{0.07\\linewidth}}}}",
           "\\toprule", "Task & Customer's opening message & Blocked call & What the checker told the agent & Result \\\\",
           "\\midrule"]
    for kind, tid, text, call, v, result in rows:
        if kind == "cost" and out[-1] != "\\midrule":
            out.append("\\midrule")
        out.append(f"{tid} & {tex(trim(text, 120))} & \\texttt{{{tex(call)}}} & {tex(trim(v, 260))} & {result} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


# ------------------------------------------------------------------ figures


def _style(ax):
    ax.yaxis.grid(True, color="#e6e5e0", linewidth=0.6)
    ax.set_axisbelow(True)
    for sp in ("top", "right"):
        ax.spines[sp].set_visible(False)
    for sp in ("left", "bottom"):
        ax.spines[sp].set_color("#c3c2b7")
    ax.tick_params(colors="#52514e", labelsize=8)


def fig_main(res: dict, path: Path) -> None:
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(6.4, 2.9))
    x = np.arange(len(MAIN))
    for i, k in enumerate(MAIN):
        a = res["arms"][k]
        mean, lo, hi = boot_ci(list(a["per_task"].values()))
        ax.bar(i - 0.18, 100 * mean, 0.34, color=COLOR[k], yerr=[[100 * (mean - lo)], [100 * (hi - mean)]],
               capsize=3, error_kw={"linewidth": 0.7, "ecolor": "#52514e"},
               label="Solved (share of tries)" if i == 0 else None)
        ax.bar(i + 0.18, 100 * a["pass_k"]["4"], 0.34, color=COLOR[k], alpha=0.45, hatch="///",
               edgecolor="white", label="Solved on all 4 tries" if i == 0 else None)
        ax.annotate(f"{100 * mean:.0f}", (i - 0.18, 100 * hi), xytext=(0, 2), textcoords="offset points",
                    ha="center", fontsize=7, color="#52514e")
        ax.annotate(f"{100 * a['pass_k']['4']:.0f}", (i + 0.18, 100 * a["pass_k"]["4"]), xytext=(0, 2),
                    textcoords="offset points", ha="center", fontsize=7, color="#52514e")
    ax.set_xticks(x)
    ax.set_xticklabels([f"{k}. {LABEL[k]}" for k in MAIN], fontsize=8)
    ax.set_ylabel("% of test tasks", fontsize=8)
    ax.set_ylim(0, 80)
    _style(ax)
    ax.legend(frameon=False, fontsize=7.5, loc="upper left")
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def fig_passk(res: dict, path: Path) -> None:
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(3.2, 2.6))
    for k in MAIN:
        pk = res["arms"][k]["pass_k"]
        ks = sorted(int(x) for x in pk)
        ax.plot(ks, [100 * pk[str(i)] for i in ks], marker="o", markersize=3.5, color=COLOR[k],
                label=f"{k}. {LABEL[k]}", linewidth=1.4)
    ax.set_xticks([1, 2, 3, 4])
    ax.set_xlabel("k (tries that must all succeed)", fontsize=8)
    ax.set_ylabel("pass$^k$ (%)", fontsize=8)
    ax.set_ylim(0, 60)
    _style(ax)
    ax.legend(frameon=False, fontsize=6.5)
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def fig_checkers(res: dict, path: Path) -> None:
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(3.2, 2.6))
    for i, k in enumerate(("B", "D")):
        g = res["arms"][k]["guard"]
        ok = g["blocked_write_calls"] - g["false_blocks"]
        ax.bar(i, ok, 0.55, color=COLOR[k], label="Other blocks" if i == 0 else None)
        ax.bar(i, g["false_blocks"], 0.55, bottom=ok, color="#3a3935",
               label="Blocked the correct action" if i == 0 else None)
        ax.annotate(f"{g['blocked_write_calls']} ({g['false_blocks']})", (i, g["blocked_write_calls"]),
                    xytext=(0, 2), textcoords="offset points", ha="center", fontsize=7, color="#52514e")
    ax.set_xticks([0, 1])
    ax.set_xticklabels(["Code checker", "AI checker"], fontsize=8)
    ax.set_ylabel("Blocked database changes", fontsize=8)
    _style(ax)
    ax.legend(frameon=False, fontsize=6.5, loc="upper left")
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


# ------------------------------------------------------------------ main


def dev_rows() -> dict:
    rows, spend = {}, 0.0
    for key, run in (("Plain", "dev_llm_agent_4omini"), ("One", "dev_guarded_code_agent_4omini"),
                     ("Two", "dev2_guarded_code_agent_4omini")):
        d = load_sims(run)
        pt = per_task(d)
        rows[key] = {"p1": pass_k(pt, 1), "p2": pass_k(pt, 2),
                     "fb": None if key == "Plain" else false_blocks(d)[1]}
    test_runs = {v["run"] for v in json.load(open(ROOT / "results" / "results.json"))["arms"].values()}
    for name in all_run_names():
        if name in test_runs:
            continue
        d = load_sims(name)
        if d:
            spend += sum((s.get("agent_cost") or 0) + (s.get("user_cost") or 0) for s in d["simulations"])
    return {"rows": rows, "spend": spend}


def main() -> int:
    import matplotlib

    matplotlib.use("Agg")
    matplotlib.rcParams.update({"font.family": "serif", "pdf.fonttype": 42})
    OUT.mkdir(parents=True, exist_ok=True)
    res = json.load(open(ROOT / "results" / "results.json", encoding="utf-8"))
    dev = dev_rows()
    (OUT / "numbers.tex").write_text("\n".join(macros(res, dev)) + "\n", encoding="utf-8")
    (OUT / "table_main.tex").write_text(table_main(res), encoding="utf-8")
    (OUT / "table_comparisons.tex").write_text(table_comparisons(res), encoding="utf-8")
    (OUT / "table_dev.tex").write_text(table_dev(dev), encoding="utf-8")
    (OUT / "table_examples.tex").write_text(
        table_examples(load_sims("test_A_plain_4omini"), load_sims("test_B_code_4omini")), encoding="utf-8")
    fig_main(res, OUT / "fig_main.pdf")
    fig_passk(res, OUT / "fig_passk.pdf")
    fig_checkers(res, OUT / "fig_checkers.pdf")
    print(f"Wrote report assets to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
