"""Build the figures, tables, and number macros for the Aegis demo report.

Reads a benchmark directory written by ``scripts/demo_benchmark.py``
(``results.json`` + ``records.jsonl``) and writes into ``--out-dir``:

- ``fig_headline.pdf``   - the three reliability failures, per system.
- ``fig_breakdown.pdf``  - answerable questions split into correct / wrong / declined.
- ``fig_templates.pdf``  - attack success per injection phrasing (dev vs held-out).
- ``numbers.tex``        - one ``\\newcommand`` per reported number.
- ``table_main.tex``     - the main results table.
- ``table_examples.tex`` - real questions where the systems behaved differently.
- ``table_dev.tex``      - dev-set results for each harness version (``--dev``).

Then compile ``report/demo/aegis_report.tex`` (which ``\\input``s all of the
above) with ``latexmk -pdf``. Every number in the PDF comes from these files.

    python scripts/build_report.py --bench report/demo_benchmark/test \\
        --dev "Original=report/demo_benchmark/dev_v0,Final=report/demo_benchmark/dev_v2a"
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

SYSTEMS = ("vanilla_rag", "raw_rag", "harnessed")
LABEL = {"vanilla_rag": "Plain RAG", "raw_rag": "RAG + citations", "harnessed": "Aegis"}
SYS_MACRO = {"vanilla_rag": "Plain", "raw_rag": "Cite", "harnessed": "Aegis"}
COND_MACRO = {"answerable": "Ans", "unanswerable": "Unans", "injection": "Inj"}
METRIC_MACRO = {
    "accuracy": "Acc",
    "wrong_answer_rate": "Wrong",
    "no_answer_rate": "NoAns",
    "answered_rate": "Answered",
    "attack_success_rate": "Asr",
}
COLORS = {"vanilla_rag": "#eda100", "raw_rag": "#1baf7a", "harnessed": "#2a78d6"}


def tex_escape(value) -> str:
    s = str(value).replace("\\", "\x00")
    for old, new in (("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"), ("_", r"\_"),
                     ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
                     ("^", r"\textasciicircum{}")):
        s = s.replace(old, new)
    s = s.replace("\x00", r"\textbackslash{}")
    # Characters pdflatex's default fonts lack.
    return s.replace("‹", "<").replace("›", ">").replace("’", "'")


def pct(x) -> str:
    return "--" if x is None else f"{100 * x:.1f}"


def pval(p) -> str:
    if p is None:
        return "--"
    return "$<$0.001" if p < 0.001 else f"{p:.3f}"


def ptext(p) -> str:
    if p is None:
        return "$p$ n/a"
    return "$p < 0.001$" if p < 0.001 else f"$p = {p:.3f}$"


def load(bench: Path) -> tuple[dict, list[dict]]:
    results = json.loads((bench / "results.json").read_text(encoding="utf-8"))
    records = [json.loads(line) for line in (bench / "records.jsonl").read_text(encoding="utf-8").splitlines()
               if line.strip()]
    return results, [r for r in records if "error" not in r]


# -------------------------------------------------------------------- numbers


def number_macros(results: dict, prefix: str = "") -> list[str]:
    """One macro per number; ``prefix`` namespaces a second model (e.g. "L")."""
    lines = [f"% Generated by scripts/build_report.py (prefix '{prefix}') -- do not edit."]

    def cmd(name: str, value: str) -> None:
        lines.append(f"\\newcommand{{\\{prefix}{name}}}{{{value}}}")

    meta = results["meta"]
    from aegis.config import resolve_model

    cmd("ModelName", tex_escape(resolve_model(meta["model"]).rsplit("/", 1)[-1]))
    cmd("JudgeName", tex_escape(meta["judge"]))
    cmd("NliName", tex_escape(meta.get("nli_model", "cross-encoder/nli-deberta-v3-base")))
    cmd("NQuestions", str(meta["n_questions"]))
    cmd("SampleSeed", str(meta["seed"]))
    cmd("SampleOffset", str(meta["offset"]))
    cmd("SampleHash", tex_escape(meta["sample_hash"]))
    cmd("TotalSpend", f"{meta.get('total_spend_usd', 0.0):.2f}")
    cmd("GeneratedOn", tex_escape(meta["generated"]))

    for key, row in results["metrics"].items():
        cond, metric = key.split("/")
        base = COND_MACRO[cond] + METRIC_MACRO[metric]
        for s in SYSTEMS:
            c = row["systems"][s]
            cmd(base + SYS_MACRO[s], pct(c["rate"]))
            cmd(base + SYS_MACRO[s] + "CI",
                "--" if c["rate"] is None else f"[{pct(c['lo'])}, {pct(c['hi'])}]")
            cmd(base + SYS_MACRO[s] + "K", str(c["k"]))
        cmd(base + "N", str(row["systems"]["harnessed"]["n"]))
        cmd(base + "PvPlain", pval(row["p_vs"]["vanilla_rag"]))
        cmd(base + "PvCite", pval(row["p_vs"]["raw_rag"]))
        # Sentence-ready forms: "$p = 0.332$" or "$p < 0.001$".
        cmd(base + "PvPlainText", ptext(row["p_vs"]["vanilla_rag"]))
        cmd(base + "PvCiteText", ptext(row["p_vs"]["raw_rag"]))

    for group, d in results.get("asr_by_template_group", {}).items():
        g = {"dev": "Dev", "heldout": "Heldout"}.get(group, group.title())
        for s in ("vanilla_rag", "harnessed"):
            c = d.get(s)
            if c:
                cmd(f"InjAsr{g}{SYS_MACRO[s]}", pct(c["rate"]))
                cmd(f"InjAsr{g}{SYS_MACRO[s]}CI", f"[{pct(c['lo'])}, {pct(c['hi'])}]")
        if d.get("harnessed"):
            cmd(f"InjAsr{g}N", str(d["harnessed"]["n"]))

    for s, c in results["cost"].items():
        have = c["usd_per_question"] is not None
        # USD per 1k questions.
        cmd(f"Cost{SYS_MACRO[s]}", f"{1000 * c['usd_per_question']:.2f}" if have else "--")
        cmd(f"Latency{SYS_MACRO[s]}", f"{c['mean_latency_s']:.1f}" if have else "--")
    plain, aegis = results["cost"]["vanilla_rag"]["usd_per_question"], results["cost"]["harnessed"]["usd_per_question"]
    cmd("CostRatio", f"{aegis / plain:.1f}" if plain and aegis else "--")
    return lines


def record_macros(records: list[dict], prefix: str = "") -> list[str]:
    """Numbers that need the per-question records, not just results.json."""
    from aegis.eval import stats

    lines: list[str] = []

    def cmd(name: str, value) -> None:
        lines.append(f"\\newcommand{{\\{prefix}{name}}}{{{value}}}")

    by = {(r["condition"], r["system"], r["qid"]): r for r in records}
    for cond, cond_tag in (("answerable", "Ans"), ("injection", "Inj")):
        for s in SYSTEMS:
            recs = [r for (c, sy, _), r in by.items() if c == cond and sy == s]
            answered = [r for r in recs if r["label"] != "NO_ANSWER"]
            m, lo, hi = stats.bootstrap_ci(
                [1.0 if r["label"] == "CORRECT" else 0.0 for r in answered], n_boot=10000
            )
            tag = f"{cond_tag}SelAcc{SYS_MACRO[s]}"
            cmd(tag, pct(m if answered else None))
            cmd(tag + "CI", f"[{pct(lo)}, {pct(hi)}]" if answered else "--")
            cmd(f"{cond_tag}Answered{SYS_MACRO[s]}K", len(answered))

    # Correct answers with the evidence removed can only come from memory.
    for s in SYSTEMS:
        recs = [r for (c, sy, _), r in by.items() if c == "unanswerable" and sy == s]
        k = sum(r["label"] == "CORRECT" for r in recs)
        cmd(f"UnansMemory{SYS_MACRO[s]}", pct(k / len(recs)) if recs else "--")

    # How Aegis handled the questions plain RAG got wrong vs. right.
    qids = sorted({q for (c, _, q) in by if c == "answerable"})
    for plain_label, tag in (("INCORRECT", "PlainWrong"), ("CORRECT", "PlainRight")):
        qs = [q for q in qids
              if by.get(("answerable", "vanilla_rag", q), {}).get("label") == plain_label
              and ("answerable", "harnessed", q) in by]
        cmd(f"{tag}N", len(qs))
        for aegis_label, suffix in (("NO_ANSWER", "Declined"), ("CORRECT", "Correct"),
                                    ("INCORRECT", "Wrong")):
            cmd(f"{tag}Aegis{suffix}",
                sum(by[("answerable", "harnessed", q)]["label"] == aegis_label for q in qs))
        declined = sum(by[("answerable", "harnessed", q)]["label"] == "NO_ANSWER" for q in qs)
        cmd(f"{tag}AegisDeclinedPct", f"{100 * declined / len(qs):.0f}" if qs else "--")
    return lines


# --------------------------------------------------------------------- tables


def table_main(results: dict) -> str:
    rows = [
        ("answerable/accuracy", "Answerable", "Correct answers", "$\\uparrow$"),
        ("answerable/wrong_answer_rate", "", "Wrong answers", "$\\downarrow$"),
        ("answerable/no_answer_rate", "", "Declined", ""),
        ("unanswerable/answered_rate", "Evidence removed", "Answered anyway", "$\\downarrow$"),
        ("unanswerable/wrong_answer_rate", "", "Answered anyway, wrong", "$\\downarrow$"),
        ("injection/attack_success_rate", "Injected corpus", "Repeated planted answer", "$\\downarrow$"),
        ("injection/accuracy", "", "Correct answers", "$\\uparrow$"),
    ]
    out = [
        "\\begin{tabular}{llrrrr}",
        "\\toprule",
        "Condition & Metric (\\%) & Plain RAG & RAG + citations & Aegis & $p$ vs.\\ plain \\\\",
        "\\midrule",
    ]
    for key, cond, name, arrow in rows:
        if key not in results["metrics"]:
            continue
        r = results["metrics"][key]
        cells = []
        for s in SYSTEMS:
            c = r["systems"][s]
            cells.append("--" if c["rate"] is None else
                         f"{pct(c['rate'])} {{\\scriptsize[{pct(c['lo'])}, {pct(c['hi'])}]}}")
        if cond and out[-1] != "\\midrule":
            out.append("\\addlinespace")
        out.append(f"{cond} & {name} {arrow} & " + " & ".join(cells)
                   + f" & {pval(r['p_vs']['vanilla_rag'])} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def _trim(text: str, n: int) -> str:
    text = " ".join((text or "").split())
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


def _clean(text: str) -> str:
    """Drop plain RAG's boilerplate lead-in and markdown so the answer shows."""
    import re

    text = re.sub(r"\*\*|__|^#+\s*", "", text or "", flags=re.MULTILINE)
    text = re.sub(r"^\s*(based on|according to) the (provided )?(context|information|chunks)"
                  r"( provided)?\s*[,:]\s*", "", text, flags=re.IGNORECASE)
    text = " ".join(text.split())
    return text[:1].upper() + text[1:]


def _around(text: str, needle: str, n: int) -> str:
    """Trim ``text`` to ``n`` chars, keeping ``needle`` visible if present."""
    text = " ".join(text.split())
    i = text.lower().find(needle.lower()) if needle else -1
    if i < 0 or i + len(needle) <= n - 1:
        return _trim(text, n)
    start = max(0, i - n // 2)
    return "…" + _trim(text[start:], n - 1)


def _attacked(r: dict) -> bool:
    """Same rule as demo_benchmark.attack_succeeded: name present and answer wrong."""
    return bool(r.get("attack_success")) and r.get("label") == "INCORRECT"


def table_examples(records: list[dict], k_each: int = 2) -> str:
    """Real test questions that show how the two systems differ, good and bad.

    Rows are chosen automatically (first question ids that fit), with filters
    that keep them honest: a "caught" error must not already contain the gold
    answer in plain RAG's reply, and the "lost" row shows Aegis's main cost.
    """
    by = {}
    for r in records:
        by.setdefault((r["condition"], r["qid"]), {})[r["system"]] = r

    def gold_in(r) -> bool:
        from aegis.eval.scorers import normalize_answer

        return normalize_answer(r["gold"]) in normalize_answer(r["response"] or "")

    shown: set[str] = set()

    def pick(cond, want, k=k_each):
        found = []
        for (c, qid), sysmap in sorted(by.items()):
            p, a = sysmap.get("vanilla_rag"), sysmap.get("harnessed")
            if len(found) < k and c == cond and qid not in shown and p and a and want(p, a):
                found.append((p, a))
                shown.add(qid)
        return found

    groups = [
        ("Injected corpus", pick(
            "injection",
            lambda p, a: _attacked(p) and not _attacked(a))),
        ("Evidence removed", pick(
            "unanswerable",
            lambda p, a: p["label"] == "INCORRECT" and a["label"] == "NO_ANSWER"
            and not gold_in(p))),
        ("Answerable: error caught", pick(
            "answerable",
            lambda p, a: p["label"] == "INCORRECT" and a["label"] != "INCORRECT"
            and not gold_in(p))),
        ("Answerable: correct answer lost", pick(
            "answerable",
            lambda p, a: p["label"] == "CORRECT" and a["label"] == "NO_ANSWER", k=1)),
    ]

    def show(r, needle=""):
        if r["label"] == "NO_ANSWER":
            return "\\emph{declined}"
        return tex_escape(_around(_clean(r["response"]), needle, 95))

    col = ">{\\raggedright\\arraybackslash}p"
    out = [f"\\begin{{tabular}}{{{col}{{0.14\\linewidth}}{col}{{0.3\\linewidth}}"
           f"{col}{{0.26\\linewidth}}{col}{{0.2\\linewidth}}}}",
           "\\toprule", "Case & Question \\textit{(gold answer)} & Plain RAG said & Aegis said \\\\",
           "\\midrule"]
    for name, pairs in groups:
        for i, (p, a) in enumerate(pairs):
            q = f"{tex_escape(_trim(p['question'], 115))} \\textit{{({tex_escape(p['gold'])})}}"
            extra, needle = "", p.get("fake_answer") or ""
            if needle:
                extra = f" {{\\scriptsize(planted: {tex_escape(needle)})}}"
            out.append(f"{name if i == 0 else ''} & {q}{extra} & {show(p, needle)} & {show(a)} \\\\")
        if pairs:
            out.append("\\addlinespace")
    if out[-1] == "\\addlinespace":
        out.pop()
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def table_dev(steps: list[tuple[str, dict]]) -> str:
    """Dev-set metrics for plain RAG, RAG + citations, and each harness version.

    ``steps`` is ``[(label, results), ...]`` in development order. The two
    baselines come from the last step (they did not change between steps).
    """
    keys = [
        ("answerable/accuracy", "Answerable: correct $\\uparrow$"),
        ("answerable/wrong_answer_rate", "Answerable: wrong $\\downarrow$"),
        ("answerable/no_answer_rate", "Answerable: declined"),
        ("unanswerable/answered_rate", "Evidence removed: answered $\\downarrow$"),
        ("injection/attack_success_rate", "Injected: planted answer $\\downarrow$"),
    ]
    last = steps[-1][1]
    head = " & ".join(["Dev metric (\\%)", "Plain", "+Cite"] + [tex_escape(lbl) for lbl, _ in steps])
    out = ["\\begin{tabular}{l" + "r" * (2 + len(steps)) + "}", "\\toprule",
           head + " \\\\", "\\midrule"]
    for key, name in keys:
        base = last["metrics"][key]["systems"]
        cells = [pct(base["vanilla_rag"]["rate"]), pct(base["raw_rag"]["rate"])]
        cells += [pct(r["metrics"][key]["systems"]["harnessed"]["rate"]) for _, r in steps]
        out.append(f"{name} & " + " & ".join(cells) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


# -------------------------------------------------------------------- figures


def _style(ax):
    ax.yaxis.grid(True, color="#e6e5e0", linewidth=0.6)
    ax.set_axisbelow(True)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)
    for spine in ("left", "bottom"):
        ax.spines[spine].set_color("#c3c2b7")
    ax.tick_params(colors="#52514e", labelsize=8)


def fig_headline(results: dict, path: Path) -> None:
    import matplotlib.pyplot as plt
    import numpy as np

    # Three failures the harness targets, then the price it pays. Showing the
    # failures without the declines would overstate the result.
    panels = [
        ("answerable/wrong_answer_rate", "Wrong answers\n(answerable)"),
        ("unanswerable/answered_rate", "Answered anyway\n(evidence removed)"),
        ("injection/attack_success_rate", "Repeated planted\nanswer (injected)"),
        ("answerable/no_answer_rate", "Declined an\nanswerable question"),
    ]
    fig, ax = plt.subplots(figsize=(6.6, 3.1))
    x = np.arange(len(panels), dtype=float)
    x[-1] += 0.45  # visual gap before the cost panel
    w = 0.26
    top = 0.0
    for j, s in enumerate(SYSTEMS):
        vals, lo, hi = [], [], []
        for key, _ in panels:
            c = results["metrics"][key]["systems"][s]
            v = 100 * (c["rate"] or 0)
            vals.append(v)
            lo.append(max(0, v - 100 * (c["lo"] or 0)))
            hi.append(max(0, 100 * (c["hi"] or 0) - v))
            top = max(top, 100 * (c["hi"] or 0))
        bars = ax.bar(x + (j - 1) * w, vals, w * 0.9, yerr=[lo, hi], capsize=2.5, color=COLORS[s],
                      label=LABEL[s], error_kw={"linewidth": 0.7, "ecolor": "#52514e"})
        for b, v in zip(bars, vals):
            ax.annotate(f"{v:.1f}", (b.get_x() + b.get_width() / 2, v), xytext=(0, 2),
                        textcoords="offset points", ha="center", fontsize=6, color="#52514e")
    ax.axvline((x[-2] + x[-1]) / 2, color="#8a8983", linewidth=0.8, linestyle="--")
    ax.set_xticks(x)
    ax.set_xticklabels([t for _, t in panels], fontsize=7.5)
    ax.set_ylabel("% of questions", fontsize=8)
    ax.set_ylim(0, max(10.0, top * 1.12))
    ax.text(x[1], ax.get_ylim()[1] * 0.97, "failures (lower is better)", ha="center", va="top",
            fontsize=7, color="#52514e")
    ax.text(x[-1], ax.get_ylim()[1] * 0.97, "cost", ha="center", va="top",
            fontsize=7, color="#52514e")
    _style(ax)
    ax.legend(frameon=False, fontsize=7.5, ncols=3, loc="upper center", bbox_to_anchor=(0.5, -0.2))
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def fig_breakdown(results: dict, path: Path) -> None:
    import matplotlib.pyplot as plt

    parts = [("answerable/accuracy", "Correct", "#2a78d6"),
             ("answerable/no_answer_rate", "Declined", "#c3c2b7"),
             ("answerable/wrong_answer_rate", "Wrong", "#e34948")]
    fig, ax = plt.subplots(figsize=(6.4, 1.9))
    for i, s in enumerate(reversed(SYSTEMS)):
        left = 0.0
        for key, name, color in parts:
            v = 100 * (results["metrics"][key]["systems"][s]["rate"] or 0)
            ax.barh(i, v, left=left, color=color, edgecolor="white", linewidth=0.8,
                    label=name if i == 0 else None, height=0.62)
            if v >= 5:
                ax.text(left + v / 2, i, f"{v:.0f}%", ha="center", va="center", fontsize=7,
                        color="white" if name != "Declined" else "#3a3935")
            left += v
    ax.set_yticks(range(len(SYSTEMS)))
    ax.set_yticklabels([LABEL[s] for s in reversed(SYSTEMS)], fontsize=8)
    ax.set_xlim(0, 100)
    ax.set_xlabel("% of answerable questions", fontsize=8)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)
    ax.tick_params(colors="#52514e", labelsize=8)
    ax.legend(frameon=False, fontsize=7.5, ncols=3, loc="upper center", bbox_to_anchor=(0.5, 1.3))
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def fig_templates(results: dict, path: Path) -> None:
    import matplotlib.pyplot as plt
    import numpy as np

    items = sorted(results.get("asr_by_template", {}).items(),
                   key=lambda kv: (kv[0].split("-")[0] != "dev", int(kv[0].split("-")[1])))
    if not items:
        return
    fig, ax = plt.subplots(figsize=(6.4, 2.6))
    x = np.arange(len(items))
    w = 0.38
    for j, s in enumerate(("vanilla_rag", "harnessed")):
        vals = [100 * ((d.get(s) or {}).get("rate") or 0) for _, d in items]
        ax.bar(x + (j - 0.5) * w, vals, w * 0.9, color=COLORS[s], label=LABEL[s])
    ax.set_xticks(x)
    ax.set_xticklabels([t for t, _ in items], fontsize=7, rotation=0)
    n_dev = sum(1 for t, _ in items if t.startswith("dev"))
    ax.axvline(n_dev - 0.5, color="#8a8983", linewidth=0.8, linestyle="--")
    ax.text(n_dev - 0.6, 97, "tuned on  ", ha="right", va="top", fontsize=7, color="#52514e")
    ax.text(n_dev - 0.4, 97, "  held out", ha="left", va="top", fontsize=7, color="#52514e")
    ax.set_ylabel("Repeated planted answer (%)", fontsize=8)
    ax.set_ylim(0, 100)
    _style(ax)
    ax.legend(frameon=False, fontsize=7.5, loc="upper right", bbox_to_anchor=(1.0, 0.88))
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def fig_models(runs: list[tuple[str, dict]], path: Path) -> None:
    """Plain RAG vs Aegis on the key metrics, one panel per model under test."""
    import matplotlib.pyplot as plt
    import numpy as np

    metrics = [
        ("answerable/wrong_answer_rate", "Wrong\n(answerable)"),
        ("unanswerable/answered_rate", "Answered,\nno evidence"),
        ("unanswerable/wrong_answer_rate", "Wrong,\nno evidence"),
        ("injection/attack_success_rate", "Planted\nanswer"),
        ("answerable/no_answer_rate", "Declined\n(cost)"),
    ]
    fig, axes = plt.subplots(1, len(runs), figsize=(6.8, 2.9), sharey=True)
    axes = np.atleast_1d(axes)
    top = max(100 * (r["metrics"][k]["systems"][s]["hi"] or 0)
              for _, r in runs for k, _ in metrics for s in ("vanilla_rag", "harnessed"))
    x = np.arange(len(metrics), dtype=float)
    x[-1] += 0.4
    w = 0.38
    for ax, (title, res) in zip(axes, runs):
        for j, s in enumerate(("vanilla_rag", "harnessed")):
            cells = [res["metrics"][k]["systems"][s] for k, _ in metrics]
            vals = [100 * (c["rate"] or 0) for c in cells]
            lo = [max(0, v - 100 * (c["lo"] or 0)) for v, c in zip(vals, cells)]
            hi = [max(0, 100 * (c["hi"] or 0) - v) for v, c in zip(vals, cells)]
            bars = ax.bar(x + (j - 0.5) * w, vals, w * 0.9, yerr=[lo, hi], capsize=2,
                          color=COLORS[s], label=LABEL[s],
                          error_kw={"linewidth": 0.6, "ecolor": "#52514e"})
            for b, v in zip(bars, vals):
                ax.annotate(f"{v:.0f}", (b.get_x() + b.get_width() / 2, v), xytext=(0, 2),
                            textcoords="offset points", ha="center", fontsize=6, color="#52514e")
        ax.axvline((x[-2] + x[-1]) / 2, color="#8a8983", linewidth=0.7, linestyle="--")
        ax.set_title(title, fontsize=9)
        ax.set_xticks(x)
        ax.set_xticklabels([t for _, t in metrics], fontsize=6.5)
        _style(ax)
    axes[0].set_ylabel("% of questions", fontsize=8)
    axes[0].set_ylim(0, max(10.0, top * 1.1))
    axes[0].legend(frameon=False, fontsize=7.5, loc="upper left")
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def _spend(dirs: list[Path], seen: set[str]) -> float:
    """Total model + judge spend over records, counting each record line once."""
    total = 0.0
    for d in dirs:
        for line in (d / "records.jsonl").read_text(encoding="utf-8").splitlines():
            if line.strip() and line not in seen:
                seen.add(line)
                rec = json.loads(line)
                total += rec.get("cost_usd", 0.0) + rec.get("judge_cost_usd", 0.0)
    return total


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--bench", required=True, help="Test-set benchmark directory.")
    ap.add_argument("--dev", default="",
                    help="Comma-separated Label=dir pairs, one per harness version, in order.")
    ap.add_argument("--bench2", default=None,
                    help="Test-set directory for a second model under test (macros prefixed L).")
    ap.add_argument("--bench2-dev", default=None,
                    help="Dev directory for the second model (counted in spend only).")
    ap.add_argument("--out-dir", default="report/demo")
    args = ap.parse_args()

    import matplotlib

    matplotlib.use("Agg")
    matplotlib.rcParams.update({"font.family": "serif", "pdf.fonttype": 42})

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    results, records = load(Path(args.bench))

    (out / "numbers.tex").write_text(
        "\n".join(number_macros(results) + record_macros(records)) + "\n", encoding="utf-8"
    )
    (out / "table_main.tex").write_text(table_main(results), encoding="utf-8")
    (out / "table_examples.tex").write_text(table_examples(records), encoding="utf-8")
    # Later dev runs reuse unchanged baseline records verbatim; count each once.
    seen: set[str] = set()
    dev_spend = 0.0
    if args.dev:
        steps = []
        for item in args.dev.split(","):
            label, path = item.split("=", 1)
            steps.append((label.strip(), load(Path(path.strip()))[0]))
        dev_spend = _spend([Path(p.split("=", 1)[1].strip()) for p in args.dev.split(",")], seen)
        (out / "table_dev.tex").write_text(table_dev(steps), encoding="utf-8")
    study = dev_spend + _spend([Path(args.bench)], seen)
    macros = [f"\\newcommand{{\\DevSpend}}{{{dev_spend:.2f}}}"]

    if args.bench2:
        results2, records2 = load(Path(args.bench2))
        macros += number_macros(results2, prefix="L") + record_macros(records2, prefix="L")
        (out / "table_main_weak.tex").write_text(table_main(results2), encoding="utf-8")
        (out / "table_examples_weak.tex").write_text(table_examples(records2), encoding="utf-8")
        fig_headline(results2, out / "fig_headline_weak.pdf")
        fig_breakdown(results2, out / "fig_breakdown_weak.pdf")
        from aegis.config import resolve_model

        def title(r: dict) -> str:
            return resolve_model(r["meta"]["model"]).rsplit("/", 1)[-1]

        fig_models([(title(results), results), (title(results2), results2)],
                   out / "fig_models.pdf")
        ldev = _spend([Path(args.bench2_dev)], seen) if args.bench2_dev else 0.0
        macros.append(f"\\newcommand{{\\LDevSpend}}{{{ldev:.2f}}}")
        study += ldev + _spend([Path(args.bench2)], seen)
    macros.append(f"\\newcommand{{\\StudySpend}}{{{study:.2f}}}")
    with (out / "numbers.tex").open("a", encoding="utf-8") as fh:
        fh.write("\n".join(macros) + "\n")

    fig_headline(results, out / "fig_headline.pdf")
    fig_breakdown(results, out / "fig_breakdown.pdf")
    fig_templates(results, out / "fig_templates.pdf")
    print(f"Wrote report assets to {out.resolve()}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
